"""Added the post_categories table

Revision ID: 1dbcb98d3ab8
Revises: bbcb0a957741
Create Date: 2017-09-11 23:42:10.233621

"""

# revision identifiers, used by Alembic.
revision = '1dbcb98d3ab8'
down_revision = 'bbcb0a957741'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_categories',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_post_categories__category_id__categories'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_post_categories__post_id__posts'),
    sa.PrimaryKeyConstraint('post_id', 'category_id', name='pk_post_categories')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_categories')
    ### end Alembic commands ###
