"""Added the on delete and on update settings

Revision ID: 500de4365b5d
Revises: 1dbcb98d3ab8
Create Date: 2017-09-22 22:31:34.147336

"""

# revision identifiers, used by Alembic.
revision = '500de4365b5d'
down_revision = '1dbcb98d3ab8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'fk_post_categories__category_id__categories', 'post_categories', type_='foreignkey')
    op.drop_constraint(u'fk_post_categories__post_id__posts', 'post_categories', type_='foreignkey')
    op.create_foreign_key('fk_post_categories__category_id__categories', 'post_categories', 'categories', ['category_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_post_categories__post_id__posts', 'post_categories', 'posts', ['post_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(u'fk_tag_id__tags', 'post_tags', type_='foreignkey')
    op.drop_constraint(u'fk_post_id__posts', 'post_tags', type_='foreignkey')
    op.create_foreign_key('fk_tag_id__tags', 'post_tags', 'tags', ['tag_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_post_id__posts', 'post_tags', 'posts', ['post_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(u'fk_url_id__urls', 'posts', type_='foreignkey')
    op.create_foreign_key('fk_url_id__urls', 'posts', 'urls', ['url_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_url_id__urls', 'posts', type_='foreignkey')
    op.create_foreign_key(u'fk_url_id__urls', 'posts', 'urls', ['url_id'], ['id'])
    op.drop_constraint('fk_post_id__posts', 'post_tags', type_='foreignkey')
    op.drop_constraint('fk_tag_id__tags', 'post_tags', type_='foreignkey')
    op.create_foreign_key(u'fk_post_id__posts', 'post_tags', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(u'fk_tag_id__tags', 'post_tags', 'tags', ['tag_id'], ['id'])
    op.drop_constraint('fk_post_categories__post_id__posts', 'post_categories', type_='foreignkey')
    op.drop_constraint('fk_post_categories__category_id__categories', 'post_categories', type_='foreignkey')
    op.create_foreign_key(u'fk_post_categories__post_id__posts', 'post_categories', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(u'fk_post_categories__category_id__categories', 'post_categories', 'categories', ['category_id'], ['id'])
    ### end Alembic commands ###
