"""Added the categories table

Revision ID: bbcb0a957741
Revises: d846dbb4149c
Create Date: 2017-09-11 22:28:59.024464

"""

# revision identifiers, used by Alembic.
revision = 'bbcb0a957741'
down_revision = 'd846dbb4149c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_categories'),
    sa.UniqueConstraint('name', name='uq_categories__name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    ### end Alembic commands ###
