"""Added the jti column to the users table

Revision ID: d846dbb4149c
Revises: a38af4b49c3b
Create Date: 2016-10-04 00:05:43.856972

"""

# revision identifiers, used by Alembic.
revision = 'd846dbb4149c'
down_revision = 'a38af4b49c3b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jti', sa.String(length=32), nullable=True))
    users = table("users", column("jti"))
    op.execute(users.update().values(jti=""))
    op.alter_column("users", "jti", nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'jti')
    ### end Alembic commands ###
